title: My Awesome Blog
author: MirRaonaq
email: miraonaq@microsoft.com
description: > # this means to ignore newlines until "baseurl:"
Just a kid from Queens

# social links
twitter_username: Mir
github_username:  MirRaonaq
theme: minima
show_excerpts: true # set to false to remove excerpts on the homepage
